import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import './overrides.css';
import './title-fixes.css';

const A='/assets/';
const products=[
  {id:'jerk-seasoning',name:'Jerk Seasoning',tag:'The heartbeat of Jamaican cooking',desc:'An authentic jerk marinade bursting with pimento, thyme, scallion, and Scotch Bonnet heat.',price:900,heat:'medium',tone:'gold',note:'Sweet heat. Smoky finish.',image:'heartbeat-of-jamaican-cooking-jerk-marinade.jpg'},
  {id:'jerk-bbq',name:'Jerk BBQ Sauce',tag:'Sweet heat. Smoky finish.',desc:'A bold fusion of classic BBQ sweetness and jerk spice for meats, wings and anything worth glazing.',price:150,heat:'medium',tone:'red',note:'Rich, smoky glaze.',image:'sweet-heat-smoky-finish-bbq-jerk-sauce.jpg'},
  {id:'mango',name:'Mango Salsa',tag:'Sweet island sunshine',desc:'A smooth tropical mango sauce with a mild finish — perfect for dipping, glazing and pairing.',price:140,heat:'mild',tone:'yellow',note:'Soft mango. Gentle warmth.',image:'sweet-island-sunshine-mango-sauce.jpg'},
  {id:'spicy-mango',name:'Spicy Mango Salsa',tag:'Sweet meets fire',desc:'Ripe mango sweetness and pepper heat, balanced for a perfectly bright sweet-spicy kick.',price:150,heat:'hot',tone:'green',note:'A bright, balanced kick.',image:'sweet-meets-fire-spicy-mango-sauce.jpg'},
  {id:'sorrel',name:'Sorrel Pepper Sauce',tag:'Tangy, spicy, unforgettable',desc:'Traditional Jamaican sorrel meets fiery peppers in a vibrant balance of tangy sweetness and heat.',price:150,heat:'hot',tone:'burgundy',note:'Bold Caribbean heat.'},
  {id:'crushed',name:'Crushed Pepper Sauce',tag:'Bring the heat. Keep the flavour.',desc:'A vibrant fiery pepper sauce designed to enhance — not overpower — every meal.',price:150,heat:'hot',tone:'black',note:'For serious pepper fans.',soon:true}
];
const heatLabels={mild:'Tups',medium:'Nuh 2 Much',hot:'Whole Heap'};

function App(){
  const [page,setPage]=useState('home'); const [cart,setCart]=useState([]); const [filter,setFilter]=useState('all'); const [sort,setSort]=useState('featured'); const [selected,setSelected]=useState(null); const [menu,setMenu]=useState(false); const [sent,setSent]=useState(false); const [toast,setToast]=useState(null);
  const showToast=(message,type='success')=>setToast({message,type,id:Date.now()});
  useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(null),4200);return()=>window.clearTimeout(timer)},[toast]);
  const add=(p, quantity=1)=>{
    if(!p||p.soon){showToast('This flavour is not available yet.','error');return false}
    const raw=Number(quantity);
    if(!Number.isFinite(raw)||raw<1){showToast('Choose a quantity of at least 1.','error');return false}
    const amount=Math.min(999999,Math.floor(raw));
    setCart(c=>{const existing=c.find(item=>item.id===p.id); return existing?c.map(item=>item.id===p.id?{...item,quantity:Math.min(999999,item.quantity+amount)}:item):[...c,{...p,quantity:amount}]});
    showToast(`${p.name} added to your selection${amount>1?` · quantity ${amount.toLocaleString()}`:''}.`,'success');
    return true;
  };
  const updateQuantity=(index, delta)=>setCart(c=>c.map((item,i)=>i===index?{...item,quantity:Math.max(1,Math.min(999999,item.quantity+delta))}:item));
  const setQuantity=(index, value)=>setCart(c=>c.map((item,i)=>i===index?{...item,quantity:Math.max(1,Math.min(999999,Number(value)||1))}:item));
  const go=p=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
  const shown=useMemo(()=>products.filter(p=>filter==='all'||p.heat===filter).sort((a,b)=>sort==='price'?a.price-b.price:sort==='newest'?b.id.localeCompare(a.id):0),[filter,sort]);
  useEffect(()=>{const onKey=e=>{if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
  return <>
    <div className="announcement">Authentically Jamaican <span>•</span> Exotic island flavours <span>•</span> JMD pricing</div>
    <header className="nav"><button className="brand" onClick={()=>go('home')} aria-label="Izelena Foods home"><img src={A+'izelena-logo.png'}/></button><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu}>Menu</button><nav className={menu?'open':''}><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('shop')}>Shop</button><button onClick={()=>go('story')}>Our Story</button><button onClick={()=>go('contact')}>Contact</button><button className="cart" onClick={()=>setSelected('cart')}>Cart <span>{cart.reduce((total,p)=>total+p.quantity,0)}</span></button></nav></header>
    {page==='home'&&<Home go={go} products={products} onHeat={h=>{setFilter(h);setPage('shop')}} openProduct={setSelected}/>} {page==='shop'&&<Shop shown={shown} filter={filter} setFilter={setFilter} sort={sort} setSort={setSort} add={add} setSelected={setSelected}/>} {page==='story'&&<Story go={go}/>} {page==='contact'&&<Contact sent={sent} setSent={setSent}/>}
    <Footer go={go}/>
    {toast&&<div className={`toast toast-${toast.type}`} role="status" aria-live="polite"><span aria-hidden="true">{toast.type==='success'?'✓':'!'}</span><p>{toast.message}</p><button type="button" aria-label="Dismiss notification" onClick={()=>setToast(null)}>×</button></div>}
    {selected==='cart'&&<CartWithQuantities cart={cart} close={()=>setSelected(null)} remove={i=>setCart(c=>c.filter((_,n)=>n!==i))} updateQuantity={updateQuantity} setQuantity={setQuantity}/>} {selected&&selected!=='cart'&&<ProductModalWithQuantity p={selected} close={()=>setSelected(null)} add={add}/>}
  </>;
}

function Home({go,products,onHeat,openProduct}){return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">From Izelena's garden to your kitchen</p><h1>Bring home the <em>bold</em> taste of Jamaica.</h1><p className="lede">Scotch Bonnet-forward sauces, seasonings and salsas inspired by family tradition — made to bring exotic island flavour to every season.</p><div className="actions"><button className="btn primary" onClick={()=>go('shop')}>Shop the flavours <span>↗</span></button><button className="text-btn" onClick={()=>go('story')}>Read our story <span>→</span></button></div><div className="hero-proof"><span>Small-batch flavour</span><span>Scotch Bonnet roots</span><span>Jamaica, always</span></div></div><div className="hero-art"><div className="burst">A little<br/><b>Jamaica</b><br/>in every bite.</div><img src={A+'izelena-face.png'} alt="Illustration of Miss Izelena"/><div className="tile-label">EXOTIC<br/>ISLAND<br/>FLAVOURS</div></div></section><section className="marquee"><span>Season your story</span><span>•</span><span>Share the flavour</span><span>•</span><span>Feed your people</span><span>•</span></section><section className="section products-section"><div className="section-head"><div><p className="eyebrow">Start here</p><h2>Find your favourite.</h2></div><button className="text-btn" onClick={()=>go('shop')}>See all flavours <span>↗</span></button></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p} openProduct={openProduct}/>)}</div></section><Scotchimeter go={go} onHeat={onHeat}/><section className="story-tease"><div className="story-image"><img src={A+'izelena-face-outline.png'} alt="Izelena face outline"/></div><div><p className="eyebrow">Flavour with roots</p><h2>Long before the brand, there was Izelena.</h2><p>In the farming district of Aboukir, St. Ann, Miss Izelena cultivated Scotch Bonnet pepper and a love of feeding people. Her family now carries that flavour and spirit forward.</p><button className="btn dark" onClick={()=>go('story')}>Discover the family story <span>↗</span></button></div></section><section className="wholesale"><p className="eyebrow">For the people who feed people</p><h2>Bring Izelena to your shelves.</h2><p>Retailer, restaurant, distributor or just flavour-curious? Let's talk.</p><button className="btn yellow" onClick={()=>go('contact')}>Wholesale enquiries <span>↗</span></button></section></main>}

function ProductCard({p,add,openProduct}){return <article className={'product-card '+p.tone}><div className="product-visual">{p.image?<img className="product-card-image" src={A+p.image} alt={p.name+' product'}/>:<span className="product-mark">{p.name.split(' ').map(x=>x[0]).join('')}</span>}<span className="heat-pill">{p.heat}</span>{p.soon&&<span className="soon">Coming soon</span>}</div><div className="product-info"><p className="eyebrow">{p.tag}</p><h3>{p.name}</h3><p>{p.desc}</p><div className="product-row"><strong>From J${p.price.toLocaleString()}</strong><button className="add-btn" onClick={e=>{e.stopPropagation();openProduct?openProduct(p):add(p)}} disabled={p.soon}>{p.soon?'Soon':'Add'} <span>+</span></button></div></div></article>}
function Shop({shown,filter,setFilter,sort,setSort,add,setSelected}){return <main className="page"><div className="page-intro"><p className="eyebrow">The flavour collection</p><h1>Shop sauces, seasonings<br/><em>and salsas.</em></h1><p>Choose a size, follow the Scotchimeter and bring Jamaican flavour to the table.</p></div><div className="shop-toolbar"><div className="filters" aria-label="Filter by heat"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='mild'?'active':''} onClick={()=>setFilter('mild')}>Mild</button><button className={filter==='medium'?'active':''} onClick={()=>setFilter('medium')}>Medium</button><button className={filter==='hot'?'active':''} onClick={()=>setFilter('hot')}>Hot</button></div><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price">Price: low to high</option><option value="newest">Newest</option></select></label></div><div className="product-grid archive">{shown.map(p=><div key={p.id} role="button" tabIndex="0" aria-label={`View ${p.name}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')setSelected(p)}} onClick={()=>setSelected(p)}><ProductCard p={p} openProduct={setSelected} add={e=>{e.stopPropagation();add(p)}}/></div>)}</div></main>}
function Scotchimeter({go,onHeat}){return <section className="scotch"><div><p className="eyebrow">The Scotchimeter</p><h2>How much heat<br/><em>are you feeling?</em></h2><p>Every pepper has a personality. Find your level and make it yours.</p><button className="btn primary" onClick={()=>go('shop')}>Shop by heat <span>↗</span></button></div><div className="heat-levels"><button onClick={()=>onHeat('mild')}><b>01</b><span className="peppers">🌶</span><h3>Tups</h3><p>Gentle warmth and easy everyday flavour.</p></button><button className="hot-level" onClick={()=>onHeat('medium')}><b>02</b><span className="peppers">🌶🌶</span><h3>Nuh 2 Much</h3><p>Balanced heat for flavour lovers.</p></button><button onClick={()=>onHeat('hot')}><b>03</b><span className="peppers">🌶🌶🌶</span><h3>Whole Heap</h3><p>Bold Caribbean fire for serious pepper fans.</p></button></div></section>}
function Story({go}){return <main className="page story-page"><div className="page-intro"><p className="eyebrow">Our story</p><h1>From a Jamaican garden<br/>to tables <em>around the world.</em></h1></div><section className="story-intro"><div className="story-portrait"><img src={A+'izelena-face.png'} alt="Miss Izelena illustration"/></div><div><p className="eyebrow">Flavour with roots</p><h2>Long before we had a brand, we had Izelena.</h2><p>Miss Izelena lived in the farming district of Aboukir, St. Ann, Jamaica and was an avid cultivator of Scotch Bonnet pepper. She loved the pepper — flavourful, fiery and full of Jamaican spirit — and she loved feeding people even more.</p><p>Today the family carries her name forward through a range rooted in the flavour she taught them to share.</p><button className="btn primary" onClick={()=>go('shop')}>Taste the legacy <span>↗</span></button></div></section><div className="values"><div><b>01</b><h3>Aboukir</h3><p>Family roots and Scotch Bonnet cultivation in St. Ann.</p></div><div><b>02</b><h3>Legacy</h3><p>Recipes and a love of feeding people passed through the family.</p></div><div><b>03</b><h3>Izelena</h3><p>Small-batch condiments putting Caribbean flavour at the centre.</p></div></div></main>}
function Contact({sent,setSent}){return <main className="page contact-page"><div className="page-intro"><p className="eyebrow">Say hello</p><h1>Let's make something<br/><em>flavourful.</em></h1><p>Retail order, wholesale enquiry or flavour question? Choose a reason so your message reaches the right person.</p></div><div className="contact-grid"><div className="contact-details"><p className="eyebrow">Find us</p><h2>Come through.</h2><p>17a WestLake Avenue<br/>Kingston 10, Jamaica</p><p><b>Jamaica</b> (658) 210-2059<br/><b>USA</b> (835) 245-7446</p><p><a href="mailto:info@izelenafoods.com">info@izelenafoods.com</a></p></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><span>✓</span><h2>Message received.</h2><p>Thanks for reaching out. We'll be in touch soon.</p><button type="button" className="text-btn" onClick={()=>setSent(false)}>Send another <span>↗</span></button></div>:<><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Phone<input type="tel" placeholder="+1 (000) 000-0000"/></label><label className="honeypot" aria-hidden="true">Website<input tabIndex="-1" autoComplete="off"/></label><label>Enquiry type<select><option>General question</option><option>Retail order support</option><option>Wholesale / distributor</option><option>Stockist opportunity</option></select></label><label>Message<textarea required rows="5" placeholder="Tell us what you're thinking..."></textarea></label><label className="check"><input required type="checkbox"/> I agree to the privacy notice for this enquiry.</label><button className="btn primary">Send message <span>↗</span></button></>}</form></div></main>}
function Footer({go}){return <footer><div className="footer-top"><img src={A+'izelena-logo.png'} alt="Izelena Foods"/><p>Exotic Island Flavours<br/>for Every Season.</p><button className="btn yellow" onClick={()=>go('shop')}>Shop the flavours <span>↗</span></button></div><div className="footer-bottom"><span>© 2026 Izelena Foods</span><div><button onClick={()=>go('shop')}>Shop</button><button onClick={()=>go('story')}>Our Story</button><button onClick={()=>go('contact')}>Contact</button></div><span>Made with Jamaican spirit.</span></div></footer>}
function CartWithQuantities({cart,close,remove,updateQuantity,setQuantity}){const totalItems=cart.reduce((total,p)=>total+p.quantity,0);const total=cart.reduce((sum,p)=>sum+p.price*p.quantity,0);return <div className="overlay" role="dialog" aria-modal="true" aria-label="Shopping cart"><aside className="drawer"><button className="close" aria-label="Close shopping cart" onClick={close}>×</button><p className="eyebrow">Your selection</p><h2>Cart <em>({totalItems})</em></h2>{cart.length===0?<div className="empty"><p>Your cart is waiting for a little island flavour.</p></div>:<>{cart.map((p,i)=><div className="cart-line" key={p.id}><div className={'mini '+p.tone}>{p.name[0]}</div><div><b>{p.name}</b><span>Unit price J${p.price.toLocaleString()}</span><span className="cart-quantity">Quantity</span><strong className="cart-subtotal">Line subtotal J${(p.price*p.quantity).toLocaleString()}</strong></div><div className="cart-actions"><div className="quantity-controls" aria-label={`${p.name} quantity`}><button type="button" aria-label={`Decrease ${p.name} quantity`} onClick={()=>updateQuantity(i,-1)}>−</button><input type="number" min="1" max="999999" value={p.quantity} aria-label={`${p.name} quantity`} onChange={e=>setQuantity(i,e.target.value)}/><button type="button" aria-label={`Increase ${p.name} quantity`} onClick={()=>updateQuantity(i,1)}>+</button></div><button className="cart-remove" onClick={()=>remove(i)}>Remove</button></div></div>)}<div className="cart-total"><span>Estimated total</span><strong>J${total.toLocaleString()}</strong></div><button className="btn primary full" disabled title="Checkout will be enabled when payment is connected">Checkout coming soon</button></>}</aside></div>}
function ProductModalWithQuantity({p,close,add}){const [quantity,setQuantity]=useState(1);useEffect(()=>setQuantity(1),[p.id]);const subtotal=p.price*quantity;return <div className="overlay" role="dialog" aria-modal="true" aria-label={`${p.name} details`}><div className="modal"><button className="close" aria-label="Close product details" onClick={close}>×</button><div className={'modal-art '+p.tone}><span>{p.name.split(' ').map(x=>x[0]).join('')}</span></div><div className="modal-content"><p className="eyebrow">{p.tag} · {heatLabels[p.heat]} heat</p><h2>{p.name}</h2><p>{p.desc}</p><label className="modal-select">Size / packaging<select><option>Retail jar · 10 oz</option><option>Family bottle · 18 oz</option><option>Food service · 1 gallon</option></select></label><strong className="modal-price">{quantity===1?'Unit price':'Subtotal'} J${subtotal.toLocaleString()} <small>{quantity>1?`(${quantity} × J$${p.price.toLocaleString()})`:''}</small></strong><div className="modal-quantity"><span>Quantity</span><div className="quantity-controls" aria-label={`${p.name} quantity`}><button type="button" aria-label={`Decrease ${p.name} quantity`} onClick={()=>setQuantity(q=>Math.max(1,q-1))}>−</button><input type="number" min="1" max="999999" value={quantity} aria-label={`${p.name} quantity`} onChange={e=>setQuantity(Math.max(1,Math.min(999999,Number(e.target.value)||1)))}/><button type="button" aria-label={`Increase ${p.name} quantity`} onClick={()=>setQuantity(q=>Math.min(999999,q+1))}>+</button></div></div><button className="btn primary full" onClick={()=>{if(add(p,quantity)!==false)close()}}>Add to cart <span>+</span></button></div></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
